[package]
name = "mkbubble"
version = "0.1.0"
edition = "2024"

[dependencies]
bpaf = "0.9.20"
image = "0.25.8"
rand = "0.9.2"
rayon = "1.11.0"

[profile.release]
opt-level = 3
# lto = "fat"
# codegen-units = 1

[target.'cfg(target_arch = "x86_64")']
rustflags = ["-C", "target-cpu=native"]
